export default {
	namespaced: true, // 네임스페이스 // 메인 변동률
	state: () => ({
		fluctuationsSlide: [
			{
				title: '농업',
				href: 'https://www.kiip.re.kr/index.do',
				kpbIndicator: 'upIndi',
				kpbIndicatorNo: '30',
				fListRemark1: '2,540',
				fListRemark2: '3,540',
				graph: '100',
				graphgap: '20',
				beforegraph: '80',
				beforegraphgap: '30',
				formerlygraph: '50',
			},
			{
				title: '석탄, 원유 및 천연가스',
				href: 'https://www.kiip.re.kr/index.do',
				kpbIndicator: 'downIndi',
				kpbIndicatorNo: '30',
				fListRemark1: '2,540',
				fListRemark2: '3,540',
				graph: '100',
				graphgap: '20',
				beforegraph: '80',
				beforegraphgap: '30',
				formerlygraph: '50',
			},
			{
				title: '금속 광업',
				href: 'https://www.kiip.re.kr/index.do',
				kpbIndicator: 'upIndi',
				kpbIndicatorNo: '30',
				fListRemark1: '2,540',
				fListRemark2: '3,540',
				graph: '100',
				graphgap: '20',
				beforegraph: '80',
				beforegraphgap: '30',
				formerlygraph: '50',
			},
			{
				title: '비금속광물 광업',
				href: 'https://www.kiip.re.kr/index.do',
				kpbIndicator: 'downIndi',
				kpbIndicatorNo: '30',
				fListRemark1: '2,540',
				fListRemark2: '3,540',
				graph: '100',
				graphgap: '20',
				beforegraph: '80',
				beforegraphgap: '30',
				formerlygraph: '50',
			},
			{
				title: '식료품 제조업',
				href: 'https://www.kiip.re.kr/index.do',
				kpbIndicator: 'downIndi',
				kpbIndicatorNo: '30',
				fListRemark1: '2,540',
				fListRemark2: '3,540',
				graph: '100',
				graphgap: '20',
				beforegraph: '80',
				beforegraphgap: '30',
				formerlygraph: '50',
			},
			{
				title: '의복, 의복 액세서리',
				href: 'https://www.kiip.re.kr/index.do',
				kpbIndicator: 'upIndi',
				kpbIndicatorNo: '30',
				fListRemark1: '2,540',
				fListRemark2: '3,540',
				graph: '100',
				graphgap: '20',
				beforegraph: '80',
				beforegraphgap: '30',
				formerlygraph: '50',
			},
			{
				title: '인쇄 및 기록매체 복제업',
				href: 'https://www.kiip.re.kr/index.do',
				kpbIndicator: 'upIndi',
				kpbIndicatorNo: '30',
				fListRemark1: '2,540',
				fListRemark2: '3,540',
				graph: '100',
				graphgap: '20',
				beforegraph: '80',
				beforegraphgap: '30',
				formerlygraph: '50',
			},
			{
				title: '화학 물질 및 화학제품',
				href: 'https://www.kiip.re.kr/index.do',
				kpbIndicator: 'upIndi',
				kpbIndicatorNo: '30',
				fListRemark1: '2,540',
				fListRemark2: '3,540',
				graph: '100',
				graphgap: '20',
				beforegraph: '80',
				beforegraphgap: '30',
				formerlygraph: '50',
			},
		],
	}),
};
