const gnbNoVar = '1';
const gnbText = '분석 서비스';
const analysis = [
	{
		path: '/front/analysis/patent',
		name: 'patent',
		component: () => import('@/views/front/analysis/Patent.vue'),
		props: true,
		meta: {
			gnbNo: gnbNoVar,
			gnb: gnbText,
			titles: '특허청별 출원동향',
			text: '속지주의를 가지는 특허 제도의 특성상 발명의 권리를 자국 외의 지역으로 확대하기 위해서는 <br />해당지역의 관할 특허청에 특허를 출원하여 등록 받아야 하는데, <br />이를 기초로 특허청 별 분석을 통해 해당 기술 또는 주체가 어떤 시장을 타겟으로 진출하고자 하는지 그 경향을 파악할 수 있습니다.',
		},
	},
	{
		path: '/front/analysis/industry',
		name: 'industry',
		component: () => import('@/views/front/analysis/Industry.vue'),
		props: true,
		meta: {
			gnbNo: gnbNoVar,
			gnb: gnbText,
			titles: '산업별 출원동향',
			text: '산업 활동의 현황을 양적으로 파악하려는 목적의 지표이며, 출원 건수가 많거나 출원 점유율이 <br />높을수록 대상 분석 항목의 산업 활동이 활발하다고 해석할 수 있습니다. <br />또한, 산업의 연도별 출원 동향을 통해 산업 발전의 시기적인 동향을 분석하고, 출원 건수의 증감을 통해 기술 트렌드를 파악할 수 있습니다.',
		},
	},
	{
		path: '/front/analysis/nationality',
		name: 'nationality',
		component: () => import('@/views/front/analysis/Nationality.vue'),
		props: true,
		meta: {
			gnbNo: gnbNoVar,
			gnb: gnbText,
			titles: '국적별 출원동향',
			text: '각 특허마다의 출원인이 속한 본래의 국적을 기준으로 출원 동향을 <br />분석함으로써 분석 대상 분야에 대한 국가별 양적, <br />질적 경쟁력을 간접적으로 비교하여 파악할 수 있습니다.',
		},
	},
	{
		path: '/front/analysis/growth',
		name: 'growth',
		component: () => import('@/views/front/analysis/Growth.vue'),
		props: true,
		meta: {
			gnbNo: gnbNoVar,
			gnb: gnbText,
			titles: '산업성장주기',
			text: '연도별 특허출원 누적 건수를 기반으로 성장 곡선을 예측하여 분석 대상의 <br />기술 분야의 현재 기술성장주기 파악과 향후 기술의 발전 동향을 파악할 수 있습니다. <br />※ 기술성장곡선은 향후 예측에 기반하며, 경우에 따라 예측이 불가능한 경우도 있습니다.',
		},
	},
	{
		path: '/front/analysis/association',
		name: 'association',
		component: () => import('@/views/front/analysis/Association.vue'),
		props: true,
		meta: {
			gnbNo: gnbNoVar,
			gnb: gnbText,
			titles: '국적간 공동출원',
			text: '서로 다른 국적의 출원인이 공동 연구개발을 통해 출원한 특허의 수를 나타내는 것으로, <br />국가간 국제 공동 연구의 활성도를 파악할 수 있고, <br />빠르게 해외 시장에 진입하려는 의도에 대한 파악이 가능할 수 있습니다.',
		},
	},
	{
		path: '/front/analysis/overseas',
		name: 'overseas',
		component: () => import('@/views/front/analysis/Overseas.vue'),
		props: true,
		meta: {
			gnbNo: gnbNoVar,
			gnb: gnbText,
			titles: '해외출원비율',
			text: '자국 특허 출원에 대하여 타국 출원 여부를 통해 국가별 기업의 글로벌 전략을 파악할 수 있습니다.<br />기술에 대한 해외시장에서의 권리확보 뿐만 아니라,<br />해외 판로 개척과 글로벌 시장 선점에 대한 의지를 확인할 수 있습니다.',
		},
	},
	{
		path: '/front/analysis/major',
		name: 'major',
		component: () => import('@/views/front/analysis/Major.vue'),
		props: true,
		meta: {
			gnbNo: gnbNoVar,
			gnb: gnbText,
			titles: '주요시장 확보율',
			text: '주요 출원국인 IP5(한국, 미국, 일본, 유럽, 중국)에 출원한 비율을 나타내며, <br />주요시장 확보율이 높은 분석 대상 분야일수록 주요 해외시장 진출 및 권리 확보를 <br />위한 특허 활동이 활발한 분야인 것으로 파악할 수 있습니다.',
		},
	},
	{
		path: '/front/analysis/foreign',
		name: 'foreign',
		component: () => import('@/views/front/analysis/Foreign.vue'),
		props: true,
		meta: {
			gnbNo: gnbNoVar,
			gnb: gnbText,
			titles: '해외시장 확보율',
			text: '기술별 출원건수에 따른 점유율로, 기술 전체에서 세부기술이 차지하는 비중을 나타냅니다. <br />국적별 특허 점유율은 분석 대상 분야의 국가별 특허 현황을 나타낸 것으로, <br />분석 대상 분야에 대한 각 국가별 집중 정도를 파악할 수 있습니다.',
		},
	},
	{
		path: '/front/analysis/average',
		name: 'average',
		component: () => import('@/views/front/analysis/Average.vue'),
		props: true,
		meta: {
			gnbNo: gnbNoVar,
			gnb: gnbText,
			titles: '연평균 성장률',
			text: '분석 대상 분야별 연평균 특허 출원의 증가율을 살펴볼 수 있으며, <br />과거에서 최근까지의 성장 정도에 따라, <br />분석 대상 분야의 향후 예측이 간접적으로 이루어질 수 있습니다.',
		},
	},
	{
		path: '/front/analysis/injury',
		name: 'injury',
		component: () => import('@/views/front/analysis/Injury.vue'),
		props: true,
		meta: {
			gnbNo: gnbNoVar,
			gnb: gnbText,
			titles: '기술 부상도',
			text: '최근년도를 기준으로 최근의 특허출원 활동량 변화를 통해 기술부상도 측정하여 <br />최근 부상하고 있는 기술 동향을 파악할 수 있습니다. <br />국가별 기술 부상도를 통해 국가별로 분석 대상 분야에 대한 최근의 개발 활성도를 분석할 수 있습니다.',
		},
	},
	{
		path: '/front/analysis/share',
		name: 'share',
		component: () => import('@/views/front/analysis/Share.vue'),
		props: true,
		meta: {
			gnbNo: gnbNoVar,
			gnb: gnbText,
			titles: '특허점유율',
			text: '기술별 출원건수에 따른 점유율로, 기술 전체에서 세부기술이 차지하는 비중을 나타냅니다.<br />국적별 특허 점유율은 분석 대상 분야의 국가별 특허 현황을 나타낸 것으로, <br />분석 대상 분야에 대한 각 국가별 집중 정도를 파악할 수 있습니다.',
		},
	},
	{
		path: '/front/analysis/barrier',
		name: 'barrier',
		component: () => import('@/views/front/analysis/Barrier.vue'),
		props: true,
		meta: {
			gnbNo: gnbNoVar,
			gnb: gnbText,
			titles: '특허 장벽도',
			text: '상위 1~5위 주요 출원인의 특허출원 점유율을 분석하여 <br />관심 산업 및 기술에 대한 진입 장벽도를 판단할 수 있습니다.',
		},
	},
	{
		path: '/front/analysis/top',
		name: 'top',
		component: () => import('@/views/front/analysis/Top.vue'),
		props: true,
		meta: {
			gnbNo: gnbNoVar,
			gnb: gnbText,
			titles: 'TOP10 출원인 분석',
			text: '현재 홈페이지에 각 기술별 출원 상위 10개의 출원인별 <br />1.출원 건수, 2.연도별 출원 현황, 3.기술별 출원 건수, 4.기술 부상도, 5.주요시장 확보율을 제공하고 있음.',
		},
	},
	{
		path: '/front/analysis/topyear',
		name: 'TopYear',
		component: () => import('@/views/front/analysis/TopYear.vue'),
		props: true,
		meta: {
			gnbNo: gnbNoVar,
			gnb: gnbText,
			titles: 'TOP10 출원인 분석',
			text: '현재 홈페이지에 각 기술별 출원 상위 10개의 출원인별 <br />1.출원 건수, 2.연도별 출원 현황, 3.기술별 출원 건수, 4.기술 부상도, 5.주요시장 확보율을 제공하고 있음.',
		},
	},
	{
		path: '/front/analysis/topindustry',
		name: 'TopInjury',
		component: () => import('@/views/front/analysis/TopInjury.vue'),
		props: true,
		meta: {
			gnbNo: gnbNoVar,
			gnb: gnbText,
			titles: 'TOP10 출원인 분석',
			text: '현재 홈페이지에 각 기술별 출원 상위 10개의 출원인별 <br />1.출원 건수, 2.연도별 출원 현황, 3.기술별 출원 건수, 4.기술 부상도, 5.주요시장 확보율을 제공하고 있음.',
		},
	},
	{
		path: '/front/analysis/topassociation',
		name: 'TopAssociation',
		component: () => import('@/views/front/analysis/TopAssociation.vue'),
		props: true,
		meta: {
			gnbNo: gnbNoVar,
			gnb: gnbText,
			titles: 'TOP10 출원인 분석',
			text: '현재 홈페이지에 각 기술별 출원 상위 10개의 출원인별 <br />1.출원 건수, 2.연도별 출원 현황, 3.기술별 출원 건수, 4.기술 부상도, 5.주요시장 확보율을 제공하고 있음.',
		},
	},
	{
		path: '/front/analysis/topmajor',
		name: 'TopMajor',
		component: () => import('@/views/front/analysis/TopMajor.vue'),
		props: true,
		meta: {
			gnbNo: gnbNoVar,
			gnb: gnbText,
			titles: 'TOP10 출원인 분석',
			text: '현재 홈페이지에 각 기술별 출원 상위 10개의 출원인별 <br />1.출원 건수, 2.연도별 출원 현황, 3.기술별 출원 건수, 4.기술 부상도, 5.주요시장 확보율을 제공하고 있음.',
		},
	},
	{
		path: '/front/analysis/crisis',
		name: 'crisis',
		component: () => import('@/views/front/analysis/Crisis.vue'),
		props: true,
		meta: {
			gnbNo: gnbNoVar,
			gnb: gnbText,
			titles: '위기신호 분석',
			text: '',
		},
	},
];
export { analysis };
